dfm/tess-atlas

.github/workflows/template_test.yml, README.md, requirements.txt, template.ipynb, tests/__init__.py, tests/test_template_notebook.py, tests/unittest_template_notebook.py
Im concerned Ill break something in `template.ipynb` while hacking so I wanted to set up some tests to ensure things still work.
=> add pytests and CI for `template.ipynb`

CHANGELOG.md, requirements.txt, tess_atlas/template.ipynb, tests/test_template_notebook.py
=> Use spoc estimates for period

requirements.txt
=> add plotly to requirements

Makefile, requirements.txt
=> updating dependencies

README.md, tess_atlas/run_toi.py
It can be useful to be able to see the errors that caused a notebook to fail.
=> Fixing readme instructions, saving failed notebooks

src/tess_atlas/data.py, src/tess_atlas/load_samples_demo.py, src/tess_atlas/run_load_samples_demo.py, src/tess_atlas/run_toi.py, src/tess_atlas/utils.py, tests/test_load_samples_demo.py
=> add notebook to demonstrate how to load saved samples

src/tess_atlas/eccenticity_reweighting.py, src/tess_atlas/plotting.py, src/tess_atlas/template.py, tests/test_template_notebook.py
=> WIP: fix eccentricity calculations

README.md, setup.py, src/tess_atlas/run_tois.py
I was getting some pathing issues. Making a cli tool makes it easier to run on TOIs.
=> make toi runner into cli tool

src/tess_atlas/plotting.py, src/tess_atlas/template.py
Code to add plot like below:
Code adapted from 
https://gallery.exoplanet.codes/en/latest/tutorials/tess/
https://docs.exoplanet.codes/en/stable/tutorials/transit/#Sampling
=> WIP: add final folded light curve plot

src/tess_atlas/run_toi.py, src/tess_atlas/run_tois.py
- add argparse to handle cli args
- add an option for the outdir for notebooks
=> improve cli interface

setup.py
=> update min lightkurve version

.github/workflows/tests.yml, setup.py, src/tess_atlas/batch_job_generator/slurm_job_generator.py, src/tess_atlas/batch_job_generator/slurm_template.sh, src/tess_atlas/notebook_preprocessors/run_toi.py, tests/test_slurm_job_generator.py
Add a module to help create batch jobs (currently just to help generate SLURM jobs).
Includes a fix to close #107 (pinning `jupyter_client`)
=> Add batch job creator module

README.md, src/tess_atlas/data/tic_entry.py, src/tess_atlas/notebook_preprocessors/run_toi.py, src/tess_atlas/notebook_preprocessors/run_tois.py, src/tess_atlas/notebook_preprocessors/toi_notebook_generator.py
=> add setup step for run_toi 

setup.py
=> fix missing req

src/tess_atlas/data/stellar_data.py
=> Retry on 503

src/tess_atlas/notebook_preprocessors/run_toi.py, src/tess_atlas/notebook_templates/toi_template.py, src/tess_atlas/utils.py
=> filter logs and fix log file

src/tess_atlas/analysis/eccenticity_reweighting.py, src/tess_atlas/analysis/model_tools.py, src/tess_atlas/analysis/stats_plotter.py, src/tess_atlas/data/__init__.py, src/tess_atlas/data/data_object.py, src/tess_atlas/data/inference_data_tools.py, src/tess_atlas/data/lightcurve_data.py, src/tess_atlas/data/planet_candidate.py, src/tess_atlas/data/stellar_data.py, src/tess_atlas/data/tic_entry.py, src/tess_atlas/notebook_preprocessors/run_load_samples_demo.py, src/tess_atlas/notebook_preprocessors/run_toi.py, src/tess_atlas/notebook_preprocessors/run_tois.py, src/tess_atlas/notebook_preprocessors/toi_notebook_generator.py, src/tess_atlas/notebook_templates/load_samples_demo.py, src/tess_atlas/notebook_templates/toi_template.py, src/tess_atlas/plotting/__init__.py, src/tess_atlas/plotting/corner_plotter.py, src/tess_atlas/plotting/matplotlib_plots.py, src/tess_atlas/plotting/plotly_plots.py, src/tess_atlas/plotting/plotter_backend.py, src/tess_atlas/plotting/plotting_utils.py, src/tess_atlas/utils.py, src/tess_atlas/webbuilder/build_pages.py
=> isort files

src/tess_atlas/notebook_templates/toi_template.py, src/tess_atlas/plotting/corner_plotter.py, src/tess_atlas/plotting/labels.py
=> adjust d and to prior

src/tess_atlas/analysis/eccenticity_reweighting.py
=> add ecc sampling fix

src/tess_atlas/slurm_job_generator/slurm_cli.py, src/tess_atlas/slurm_job_generator/slurm_job_generator.py, src/tess_atlas/slurm_job_generator/slurm_template.sh, src/tess_atlas/slurm_job_generator/submit_template.sh
- break up toi list to batches
- add submitter
=> slurm array job limit fix

src/tess_atlas/data/lightcurve_data.py, src/tess_atlas/utils.py
=> add scratch dir

setup.py, src/tess_atlas/api/download_analysed_toi.py
This allows users to download FITs and analysed TOIs using `download_toi <toi_number>`
=> add download-analysed-toi feature

src/tess_atlas/analysis/model_tools.py, src/tess_atlas/plotting/matplotlib_plots.py
=> compute GP in post-proc

src/tess_atlas/notebook_templates/toi_template.py
For #173 (had forgotten to commit change to model!)
=> + save pointer to gp

.gitignore, src/tess_atlas/data/inference_data_tools.py, src/tess_atlas/plotting/corner_plotter.py, src/tess_atlas/plotting/histogram_plotter.py, src/tess_atlas/plotting/labels.py, src/tess_atlas/plotting/plotting_utils.py
=> + corner formatting fix

src/tess_atlas/plotting/extra_plotting/ci.py, src/tess_atlas/plotting/matplotlib_plots.py
Close #127
Before
This commit 
Note: maybe the GP is over-fitting the data? I think the GP may be fitting the transit signal
=> + multiplanet phase plot fix

src/tess_atlas/data/inference_data_tools.py
=> + fix idata saving

src/tess_atlas/notebook_templates/toi_template.py, src/tess_atlas/plotting/corner_plotter.py, src/tess_atlas/plotting/matplotlib_plots.py, src/tess_atlas/plotting/plotting_utils.py
+ improve single-transit corner plotting 
+ allow initial optimized params to be plotted with phase and corner plot
+ make default phase plot use histogrammed raw data without errorbars
=> + plotting fixes

src/tess_atlas/data/lightcurve_data.py, src/tess_atlas/plotting/matplotlib_plots.py
Adds diagnostic plot to check the different observing periods of the data. In the below, there are 3 observing periods, marked in gray boxes in the below plot
=> + obs period diagnostic plot

src/tess_atlas/data/lightcurve_data.py
=> Raise an error if lk search fails

src/tess_atlas/data/exofop.py, src/tess_atlas/data/lightcurve_data.py
=> check TIC has lk data before creating a notebook for it

src/tess_atlas/data/exofop.py, src/tess_atlas/webbuilder/make_run_stats_page.py, src/tess_atlas/webbuilder/make_tois_homepage.py, src/tess_atlas/webbuilder/template/conf.py, src/tess_atlas/webbuilder/template/content/toi_fits.rst
=> web improvements

setup.py, src/tess_atlas/notebook_templates/toi_template.py
=> add mem profiling + reduce number of points for phase plot

setup.py, src/tess_atlas/analysis/model_tools.py, src/tess_atlas/data/data_object.py, src/tess_atlas/data/data_utils.py, src/tess_atlas/data/inference_data_tools.py, src/tess_atlas/data/lightcurve_data.py, src/tess_atlas/data/planet_candidate.py, src/tess_atlas/data/stellar_data.py, src/tess_atlas/data/tic_entry.py, src/tess_atlas/notebook_templates/toi_template.py, src/tess_atlas/plotting/corner_plotter.py, src/tess_atlas/plotting/diagnostic_plotter.py, src/tess_atlas/plotting/plotting_utils.py
- catch exception for corner plots
- add _repr_html_ for some data object classes (pretty print in notebooks)
- remove whitespace from notebook
- add collapsable cell for model and diagnostic stuff
- reduce number of points to make posterior predictive check with (for memory issues)
=> Minor notebook improvements

src/tess_atlas/data/inference_data_tools.py, src/tess_atlas/data/planet_candidate.py, src/tess_atlas/notebook_templates/toi_template.py, src/tess_atlas/plotting/__init__.py, src/tess_atlas/plotting/corner_plotter.py, src/tess_atlas/plotting/diagnostic_plotter.py, src/tess_atlas/plotting/labels.py, src/tess_atlas/plotting/plotting_utils.py
Attempts to fix #83 
Almost there! Atm I think that the model is being offset incorrectly somewhere
=> reparameterization t0 to tmin 

src/tess_atlas/data/data_utils.py, src/tess_atlas/data/lightcurve_data.py, src/tess_atlas/notebook_templates/toi_template.py, src/tess_atlas/plotting/__init__.py, src/tess_atlas/plotting/diagnostic_plotter.py, src/tess_atlas/plotting/labels.py
Closes #223 
- custom remove outliers to help with sigma-clipping issue
- filter data outside transits if len(lc) > 100,000
Motivation for the threshold length 100,000: 
This will help speed up ~ 500 analyses 
Need to monitor if this all works with some example TOIs
|id     |toi_numbers | note|
|-----|-------------|-----|
0|103|basic|
1|178|three-planet|
2|237|multimode|
3|1812|single-transit|
4|102|largedata|
```
=> + lightcurve data preprocessing 

src/tess_atlas/plotting/diagnostic_plotter.py, src/tess_atlas/plotting/phase_plotter.py, src/tess_atlas/webbuilder/make_run_stats_page.py
=> Add image to paginated table

.gitignore, src/tess_atlas/data/exofop/__init__.py, src/tess_atlas/webbuilder/page_builder.py, tests/test_webbuild.py
=> add test for webbuild

tests/test_minmax/test_single_transit_setter.py, tests/test_minmax/test_tmintmax.py
=> add start of min-max test

src/tess_atlas/analysis/transit_model.py, src/tess_atlas/notebook_preprocessors/paths.py, src/tess_atlas/notebook_preprocessors/toi_notebook_generator.py, src/tess_atlas/notebook_templates/toi_template.py
=> move transit model to its own file
